name: Galactic
version: 1.0-SNAPSHOT
main: me.shinybless.Galactic.Main
authors: [ ShinyBless ]
api-version: 1.16

commands:
  nofall:
  hasteyboys:
  cutclean:
  switcheroo:
  superheroes:
  skyoff:
  underoff:
  bowless:
  scens:
  config:
  staffconfig:
  mute:
  unmute:
  muteall:
  jail:
  unjail:
  start:
  team:
  teamchat:
    aliases: tc
  staffchat:
    aliases: sc
  captains:
  choose:
  towers:
  dropiron:
  droplapis:
  broadcast:
    aliases: bc
  whitelist:
  givepowers:
  clearchat:
  teaminventory:
    aliases:
      - ti
      - bp
      - backpack
  helpop:

  towerswars:
